apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-qm-cpu-serial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-qm
  template:
    metadata:
      labels:
        app: quick-qm
    spec:
      containers:
      - name: quick
        image: kkricksdsu/quick@sha256:c85bb36129fb52d3c365fc1634c99205a3ee47e58a88e295c955ac90d9cf232a
        command: ["/bin/bash", "-c", "./runtest --serial --full && sleep 3600"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
