apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-qm-cuda-serial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-qm
  template:
    metadata:
      labels:
        app: quick-qm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080-Ti
      containers:
      - name: rclone
        image: rclone/rclone:latest
        command: ["rclone", "ls", "nrp-s3:"]
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 250Mi
        volumeMounts:
        - name: rclone
          mountPath: "/config/rclone/"
          readOnly: true
      - name: quick
        image: kkricksdsu/quick@sha256:62479688e5b3bfac64b4ec3db390df197d5fb6fdc853dfe8045164704f4567c2
        command: ["/bin/bash", "-c", "./runtest --cuda --full && sleep 3600"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu: 1
          requests:
            cpu: "1"
            memory: "1Gi"
            nvidia.com/gpu: 1
      restartPolicy: OnFailure
      volumes:
      - name: rclone
        secret:
          secretName: rclone
